# Fuzzel Configuration
font=JetBrainsMono Nerd Font:size=12
icon-theme=Papirus-Dark
prompt="❯ "
terminal=foot  # Cambia por tu terminal favorita (kitty, alacritty, etc.)
width=25
horizontal-pad=20
vertical-pad=15
inner-pad=10

[colors]
background=282a36ff
text=f8f8f2ff
match=50fa7bff
selection=44475aff
selection-text=f8f8f2ff
border=bd93f9ff

[border]
width=2
radius=15

[drun]
filter-desktop=yes
